### ISSUE TITLE
Get a list of keywords

### ISSUE THREAD

**Issue by raldridge11** [raldridge11/FortranVS#1]
A list of the Fortran keywords needs to be compiled and parsed, https://gcc.gnu.org/onlinedocs/gfortran/, has documentation. Preferably, the compiling of this list would be automated, via Python, and translated into whatever the VSIX SDK expects (e.g. xml).

**Comment by rjgtorres** [comment]
Hello!
Gtksourceview fortran.lang file has most fortran keywords and I have added the ones i found missing in: [my_fortran.lang](https://github.com/rjgtorres/GEDIT_CONFIG/blob/master/fortran.lang). 
This may only work for gtk programs but it is easy to copy the list.
Hope it helps.
 Regards,
Ricardo

**Comment by raldridge11** [comment]
@rjgtorres, that is definitely helpful. I don't want to reinvent the wheel if it already exists 😃.

**Comment by raldridge11** [comment]
In VS 2015 Update 1+, support for Textmate grammars has been [added](https://docs.microsoft.com/en-us/visualstudio/ide/adding-visual-studio-editor-support-for-other-languages). A Textmate grammar for [Fortran](https://github.com/textmate/fortran.tmbundle) has already been created. To not duplicate work, FortranVS will use the Textmate grammar files for Fortran.
